// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	dataitem "github.com/struckoff/kvstore/router/dataitem"

	rpcapi "github.com/struckoff/kvstore/router/rpcapi"
)

// DataItemFromRpc is an autogenerated mock type for the DataItemFromRpc type
type DataItemFromRpc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *DataItemFromRpc) Execute(_a0 *rpcapi.DataItem) dataitem.DataItem {
	ret := _m.Called(_a0)

	var r0 dataitem.DataItem
	if rf, ok := ret.Get(0).(func(*rpcapi.DataItem) dataitem.DataItem); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dataitem.DataItem)
		}
	}

	return r0
}
