// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	dataitem "github.com/struckoff/kvstore/router/dataitem"
)

// NewDataItemFunc is an autogenerated mock type for the NewDataItemFunc type
type NewDataItemFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *NewDataItemFunc) Execute(_a0 string, _a1 uint64) (dataitem.DataItem, error) {
	ret := _m.Called(_a0, _a1)

	var r0 dataitem.DataItem
	if rf, ok := ret.Get(0).(func(string, uint64) dataitem.DataItem); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(dataitem.DataItem)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, uint64) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
