// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	rpcapi "github.com/struckoff/kvstore/router/rpcapi"
)

// RPCBalancerServer is an autogenerated mock type for the RPCBalancerServer type
type RPCBalancerServer struct {
	mock.Mock
}

// RPCHeartbeat provides a mock function with given fields: _a0, _a1
func (_m *RPCBalancerServer) RPCHeartbeat(_a0 context.Context, _a1 *rpcapi.Ping) (*rpcapi.Empty, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *rpcapi.Empty
	if rf, ok := ret.Get(0).(func(context.Context, *rpcapi.Ping) *rpcapi.Empty); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rpcapi.Empty)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *rpcapi.Ping) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RPCRegister provides a mock function with given fields: _a0, _a1
func (_m *RPCBalancerServer) RPCRegister(_a0 context.Context, _a1 *rpcapi.NodeMeta) (*rpcapi.Empty, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *rpcapi.Empty
	if rf, ok := ret.Get(0).(func(context.Context, *rpcapi.NodeMeta) *rpcapi.Empty); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rpcapi.Empty)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *rpcapi.NodeMeta) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
