// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	rpcapi "github.com/struckoff/kvstore/router/rpcapi"
)

// RPCCapacityClient is an autogenerated mock type for the RPCCapacityClient type
type RPCCapacityClient struct {
	mock.Mock
}

// RPCGet provides a mock function with given fields: ctx, in, opts
func (_m *RPCCapacityClient) RPCGet(ctx context.Context, in *rpcapi.Empty, opts ...grpc.CallOption) (*rpcapi.Capacity, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *rpcapi.Capacity
	if rf, ok := ret.Get(0).(func(context.Context, *rpcapi.Empty, ...grpc.CallOption) *rpcapi.Capacity); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rpcapi.Capacity)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *rpcapi.Empty, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
