// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	rpcapi "github.com/struckoff/kvstore/router/rpcapi"
)

// RPCCapacityServer is an autogenerated mock type for the RPCCapacityServer type
type RPCCapacityServer struct {
	mock.Mock
}

// RPCGet provides a mock function with given fields: _a0, _a1
func (_m *RPCCapacityServer) RPCGet(_a0 context.Context, _a1 *rpcapi.Empty) (*rpcapi.Capacity, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *rpcapi.Capacity
	if rf, ok := ret.Get(0).(func(context.Context, *rpcapi.Empty) *rpcapi.Capacity); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rpcapi.Capacity)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *rpcapi.Empty) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
