// Code generated by protoc-gen-go. DO NOT EDIT.
// source: explore.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StoreReq struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreReq) Reset()         { *m = StoreReq{} }
func (m *StoreReq) String() string { return proto.CompactTextString(m) }
func (*StoreReq) ProtoMessage()    {}
func (*StoreReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e22095251b76ab96, []int{0}
}

func (m *StoreReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreReq.Unmarshal(m, b)
}
func (m *StoreReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreReq.Marshal(b, m, deterministic)
}
func (m *StoreReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreReq.Merge(m, src)
}
func (m *StoreReq) XXX_Size() int {
	return xxx_messageInfo_StoreReq.Size(m)
}
func (m *StoreReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreReq.DiscardUnknown(m)
}

var xxx_messageInfo_StoreReq proto.InternalMessageInfo

func (m *StoreReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *StoreReq) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type StoreRes struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreRes) Reset()         { *m = StoreRes{} }
func (m *StoreRes) String() string { return proto.CompactTextString(m) }
func (*StoreRes) ProtoMessage()    {}
func (*StoreRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_e22095251b76ab96, []int{1}
}

func (m *StoreRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreRes.Unmarshal(m, b)
}
func (m *StoreRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreRes.Marshal(b, m, deterministic)
}
func (m *StoreRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreRes.Merge(m, src)
}
func (m *StoreRes) XXX_Size() int {
	return xxx_messageInfo_StoreRes.Size(m)
}
func (m *StoreRes) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreRes.DiscardUnknown(m)
}

var xxx_messageInfo_StoreRes proto.InternalMessageInfo

type ReceiveReq struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiveReq) Reset()         { *m = ReceiveReq{} }
func (m *ReceiveReq) String() string { return proto.CompactTextString(m) }
func (*ReceiveReq) ProtoMessage()    {}
func (*ReceiveReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e22095251b76ab96, []int{2}
}

func (m *ReceiveReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiveReq.Unmarshal(m, b)
}
func (m *ReceiveReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiveReq.Marshal(b, m, deterministic)
}
func (m *ReceiveReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveReq.Merge(m, src)
}
func (m *ReceiveReq) XXX_Size() int {
	return xxx_messageInfo_ReceiveReq.Size(m)
}
func (m *ReceiveReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveReq proto.InternalMessageInfo

func (m *ReceiveReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type ReceiveRes struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiveRes) Reset()         { *m = ReceiveRes{} }
func (m *ReceiveRes) String() string { return proto.CompactTextString(m) }
func (*ReceiveRes) ProtoMessage()    {}
func (*ReceiveRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_e22095251b76ab96, []int{3}
}

func (m *ReceiveRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiveRes.Unmarshal(m, b)
}
func (m *ReceiveRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiveRes.Marshal(b, m, deterministic)
}
func (m *ReceiveRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveRes.Merge(m, src)
}
func (m *ReceiveRes) XXX_Size() int {
	return xxx_messageInfo_ReceiveRes.Size(m)
}
func (m *ReceiveRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveRes.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveRes proto.InternalMessageInfo

func (m *ReceiveRes) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ReceiveRes) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type NodeMeta struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
	RPCAddress           string   `protobuf:"bytes,3,opt,name=RPCAddress,proto3" json:"RPCAddress,omitempty"`
	Power                float64  `protobuf:"fixed64,4,opt,name=Power,proto3" json:"Power,omitempty"`
	Capacity             float64  `protobuf:"fixed64,5,opt,name=Capacity,proto3" json:"Capacity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeMeta) Reset()         { *m = NodeMeta{} }
func (m *NodeMeta) String() string { return proto.CompactTextString(m) }
func (*NodeMeta) ProtoMessage()    {}
func (*NodeMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_e22095251b76ab96, []int{4}
}

func (m *NodeMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeMeta.Unmarshal(m, b)
}
func (m *NodeMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeMeta.Marshal(b, m, deterministic)
}
func (m *NodeMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeMeta.Merge(m, src)
}
func (m *NodeMeta) XXX_Size() int {
	return xxx_messageInfo_NodeMeta.Size(m)
}
func (m *NodeMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeMeta.DiscardUnknown(m)
}

var xxx_messageInfo_NodeMeta proto.InternalMessageInfo

func (m *NodeMeta) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *NodeMeta) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *NodeMeta) GetRPCAddress() string {
	if m != nil {
		return m.RPCAddress
	}
	return ""
}

func (m *NodeMeta) GetPower() float64 {
	if m != nil {
		return m.Power
	}
	return 0
}

func (m *NodeMeta) GetCapacity() float64 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

type NodeMetas struct {
	Metas                []*NodeMeta `protobuf:"bytes,1,rep,name=Metas,proto3" json:"Metas,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *NodeMetas) Reset()         { *m = NodeMetas{} }
func (m *NodeMetas) String() string { return proto.CompactTextString(m) }
func (*NodeMetas) ProtoMessage()    {}
func (*NodeMetas) Descriptor() ([]byte, []int) {
	return fileDescriptor_e22095251b76ab96, []int{5}
}

func (m *NodeMetas) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeMetas.Unmarshal(m, b)
}
func (m *NodeMetas) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeMetas.Marshal(b, m, deterministic)
}
func (m *NodeMetas) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeMetas.Merge(m, src)
}
func (m *NodeMetas) XXX_Size() int {
	return xxx_messageInfo_NodeMetas.Size(m)
}
func (m *NodeMetas) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeMetas.DiscardUnknown(m)
}

var xxx_messageInfo_NodeMetas proto.InternalMessageInfo

func (m *NodeMetas) GetMetas() []*NodeMeta {
	if m != nil {
		return m.Metas
	}
	return nil
}

type ExploreReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExploreReq) Reset()         { *m = ExploreReq{} }
func (m *ExploreReq) String() string { return proto.CompactTextString(m) }
func (*ExploreReq) ProtoMessage()    {}
func (*ExploreReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e22095251b76ab96, []int{6}
}

func (m *ExploreReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExploreReq.Unmarshal(m, b)
}
func (m *ExploreReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExploreReq.Marshal(b, m, deterministic)
}
func (m *ExploreReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExploreReq.Merge(m, src)
}
func (m *ExploreReq) XXX_Size() int {
	return xxx_messageInfo_ExploreReq.Size(m)
}
func (m *ExploreReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ExploreReq.DiscardUnknown(m)
}

var xxx_messageInfo_ExploreReq proto.InternalMessageInfo

type ExploreRes struct {
	Keys                 []string `protobuf:"bytes,1,rep,name=Keys,proto3" json:"Keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExploreRes) Reset()         { *m = ExploreRes{} }
func (m *ExploreRes) String() string { return proto.CompactTextString(m) }
func (*ExploreRes) ProtoMessage()    {}
func (*ExploreRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_e22095251b76ab96, []int{7}
}

func (m *ExploreRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExploreRes.Unmarshal(m, b)
}
func (m *ExploreRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExploreRes.Marshal(b, m, deterministic)
}
func (m *ExploreRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExploreRes.Merge(m, src)
}
func (m *ExploreRes) XXX_Size() int {
	return xxx_messageInfo_ExploreRes.Size(m)
}
func (m *ExploreRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ExploreRes.DiscardUnknown(m)
}

var xxx_messageInfo_ExploreRes proto.InternalMessageInfo

func (m *ExploreRes) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

func init() {
	proto.RegisterType((*StoreReq)(nil), "proto.StoreReq")
	proto.RegisterType((*StoreRes)(nil), "proto.StoreRes")
	proto.RegisterType((*ReceiveReq)(nil), "proto.ReceiveReq")
	proto.RegisterType((*ReceiveRes)(nil), "proto.ReceiveRes")
	proto.RegisterType((*NodeMeta)(nil), "proto.NodeMeta")
	proto.RegisterType((*NodeMetas)(nil), "proto.NodeMetas")
	proto.RegisterType((*ExploreReq)(nil), "proto.ExploreReq")
	proto.RegisterType((*ExploreRes)(nil), "proto.ExploreRes")
}

func init() {
	proto.RegisterFile("explore.proto", fileDescriptor_e22095251b76ab96)
}

var fileDescriptor_e22095251b76ab96 = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x65, 0xdb, 0x46, 0x93, 0x69, 0xd5, 0x3a, 0x78, 0x08, 0x39, 0x48, 0x58, 0x10, 0x72, 0x90,
	0x22, 0xd1, 0x3f, 0x20, 0xa9, 0x87, 0x52, 0x95, 0x30, 0x82, 0xf7, 0xd8, 0x0e, 0x52, 0x28, 0xa6,
	0xdd, 0x8d, 0x1f, 0xfd, 0x03, 0xfe, 0x43, 0xff, 0x8f, 0x64, 0x37, 0xdb, 0x96, 0xd6, 0x83, 0xa7,
	0xcc, 0x7b, 0x2f, 0x6f, 0xe7, 0xed, 0x5b, 0x38, 0xe2, 0xaf, 0xc5, 0xbc, 0x54, 0x3c, 0x58, 0xa8,
	0xb2, 0x2a, 0xd1, 0x33, 0x1f, 0x99, 0x82, 0xff, 0x54, 0x95, 0x8a, 0x89, 0x97, 0xd8, 0x87, 0xf6,
	0x98, 0x57, 0xa1, 0x88, 0x45, 0x12, 0x50, 0x3d, 0xe2, 0x19, 0x78, 0xcf, 0xc5, 0xfc, 0x9d, 0xc3,
	0x56, 0x2c, 0x92, 0x1e, 0x59, 0x20, 0x61, 0xed, 0xd1, 0xf2, 0x1c, 0x80, 0x78, 0xc2, 0xb3, 0x8f,
	0xbf, 0x4f, 0x90, 0x37, 0x5b, 0xba, 0xfe, 0xf7, 0x86, 0x6f, 0x01, 0xfe, 0x63, 0x39, 0xe5, 0x07,
	0xae, 0x0a, 0x3c, 0x86, 0xd6, 0x68, 0xd8, 0x78, 0x5a, 0xa3, 0x21, 0x86, 0x70, 0x78, 0x3b, 0x9d,
	0x2a, 0xd6, 0xda, 0x98, 0x02, 0x72, 0x10, 0xeb, 0x30, 0x79, 0xe6, 0xc4, 0xb6, 0x11, 0xb7, 0x98,
	0x7a, 0x59, 0x5e, 0x7e, 0xb2, 0x0a, 0x3b, 0xb1, 0x48, 0x04, 0x59, 0x80, 0x11, 0xf8, 0x59, 0xb1,
	0x28, 0x26, 0xb3, 0x6a, 0x15, 0x7a, 0x46, 0x58, 0x63, 0x99, 0x42, 0xe0, 0x72, 0x68, 0xbc, 0x00,
	0xcf, 0x0c, 0xa1, 0x88, 0xdb, 0x49, 0x37, 0x3d, 0xb1, 0x4d, 0x0e, 0xdc, 0x0f, 0x64, 0x55, 0xd9,
	0x03, 0xb8, 0xb3, 0x55, 0x13, 0x2f, 0x65, 0xbc, 0x85, 0x34, 0x22, 0x74, 0xc6, 0xbc, 0xb2, 0x27,
	0x04, 0x64, 0xe6, 0xf4, 0x47, 0x40, 0x97, 0xf2, 0xec, 0x7e, 0xa6, 0x2b, 0x7e, 0x63, 0x85, 0x97,
	0xe0, 0x53, 0x9e, 0x99, 0x86, 0xd1, 0xed, 0x70, 0x6f, 0x14, 0xed, 0x10, 0x1a, 0x53, 0x73, 0xe7,
	0xa6, 0x63, 0x3c, 0x6d, 0xe4, 0xcd, 0x9b, 0x44, 0x7b, 0x94, 0xf3, 0x34, 0xb1, 0xd6, 0x9e, 0x4d,
	0xe8, 0x68, 0x8f, 0xd2, 0x78, 0x65, 0x42, 0x12, 0xbf, 0xd6, 0x31, 0x15, 0xee, 0x5e, 0x3e, 0xea,
	0xef, 0x10, 0xfa, 0xe5, 0xc0, 0x10, 0xd7, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa4, 0xc6, 0x78,
	0xab, 0x79, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RPCListenerClient is the client API for RPCListener service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RPCListenerClient interface {
	RPCStore(ctx context.Context, in *StoreReq, opts ...grpc.CallOption) (*StoreRes, error)
	RPCReceive(ctx context.Context, in *ReceiveReq, opts ...grpc.CallOption) (*ReceiveRes, error)
	RPCExplore(ctx context.Context, in *ExploreReq, opts ...grpc.CallOption) (*ExploreRes, error)
	RPCRegister(ctx context.Context, in *NodeMeta, opts ...grpc.CallOption) (*NodeMetas, error)
}

type rPCListenerClient struct {
	cc grpc.ClientConnInterface
}

func NewRPCListenerClient(cc grpc.ClientConnInterface) RPCListenerClient {
	return &rPCListenerClient{cc}
}

func (c *rPCListenerClient) RPCStore(ctx context.Context, in *StoreReq, opts ...grpc.CallOption) (*StoreRes, error) {
	out := new(StoreRes)
	err := c.cc.Invoke(ctx, "/proto.RPCListener/RPCStore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCListenerClient) RPCReceive(ctx context.Context, in *ReceiveReq, opts ...grpc.CallOption) (*ReceiveRes, error) {
	out := new(ReceiveRes)
	err := c.cc.Invoke(ctx, "/proto.RPCListener/RPCReceive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCListenerClient) RPCExplore(ctx context.Context, in *ExploreReq, opts ...grpc.CallOption) (*ExploreRes, error) {
	out := new(ExploreRes)
	err := c.cc.Invoke(ctx, "/proto.RPCListener/RPCExplore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCListenerClient) RPCRegister(ctx context.Context, in *NodeMeta, opts ...grpc.CallOption) (*NodeMetas, error) {
	out := new(NodeMetas)
	err := c.cc.Invoke(ctx, "/proto.RPCListener/RPCRegister", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RPCListenerServer is the server API for RPCListener service.
type RPCListenerServer interface {
	RPCStore(context.Context, *StoreReq) (*StoreRes, error)
	RPCReceive(context.Context, *ReceiveReq) (*ReceiveRes, error)
	RPCExplore(context.Context, *ExploreReq) (*ExploreRes, error)
	RPCRegister(context.Context, *NodeMeta) (*NodeMetas, error)
}

// UnimplementedRPCListenerServer can be embedded to have forward compatible implementations.
type UnimplementedRPCListenerServer struct {
}

func (*UnimplementedRPCListenerServer) RPCStore(ctx context.Context, req *StoreReq) (*StoreRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RPCStore not implemented")
}
func (*UnimplementedRPCListenerServer) RPCReceive(ctx context.Context, req *ReceiveReq) (*ReceiveRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RPCReceive not implemented")
}
func (*UnimplementedRPCListenerServer) RPCExplore(ctx context.Context, req *ExploreReq) (*ExploreRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RPCExplore not implemented")
}
func (*UnimplementedRPCListenerServer) RPCRegister(ctx context.Context, req *NodeMeta) (*NodeMetas, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RPCRegister not implemented")
}

func RegisterRPCListenerServer(s *grpc.Server, srv RPCListenerServer) {
	s.RegisterService(&_RPCListener_serviceDesc, srv)
}

func _RPCListener_RPCStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCListenerServer).RPCStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RPCListener/RPCStore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCListenerServer).RPCStore(ctx, req.(*StoreReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCListener_RPCReceive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCListenerServer).RPCReceive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RPCListener/RPCReceive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCListenerServer).RPCReceive(ctx, req.(*ReceiveReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCListener_RPCExplore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExploreReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCListenerServer).RPCExplore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RPCListener/RPCExplore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCListenerServer).RPCExplore(ctx, req.(*ExploreReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPCListener_RPCRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeMeta)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCListenerServer).RPCRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RPCListener/RPCRegister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCListenerServer).RPCRegister(ctx, req.(*NodeMeta))
	}
	return interceptor(ctx, in, info, handler)
}

var _RPCListener_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.RPCListener",
	HandlerType: (*RPCListenerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RPCStore",
			Handler:    _RPCListener_RPCStore_Handler,
		},
		{
			MethodName: "RPCReceive",
			Handler:    _RPCListener_RPCReceive_Handler,
		},
		{
			MethodName: "RPCExplore",
			Handler:    _RPCListener_RPCExplore_Handler,
		},
		{
			MethodName: "RPCRegister",
			Handler:    _RPCListener_RPCRegister_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "explore.proto",
}
